language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "fang_and_bone-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: fang-and-bone
  api_key:
    secure: ifPYvg5us7akfH6eKTHa4BoTuTtYVAyoF09fJhJbyUCKj8rJ3QxYnQFmoeqsY6jswrs+ImVChc5QYGkvn4w/NBziVHmtMoDOLeyj0ebRheB3Pob8iQRCdcSIiVnvq1xB31/9AyoqBrOW5raVLeL5bkxWrpNZSVD+7O5WCrB69zVh/qZZ077WUtdJ4MwW4UC3WrCiHU8u7nNNEULyVuVJXvWu0YFbODXbBb4oqJ9o6mxKrqpbgSq/LL0ZbVeeP1X6u6n5z7D6eOQzI60D+wXogCQZAQP3W5XNTbOg71ZQkT0rFiaQYVnbgjk7ClTVZE6fNVCeKD+Cnc9gQxHAfFsJDjEBimonw0fhEdKw94P2Dsi7O0TyIL64d4pdMF5mdFE8dSyCbN001m5+6J201hxhWK6liIEJfSrduDFTR1nzSTKUb1U1WNyWP5sj4eurxK3zf+J/og9N58UwT7woFf6SByBAnEv17QW/MiqK2yXbSOa3kw5OyfaLrRfPnrJwQtZsrNjQ3Z8AwCxaXFOdqLipXbY9QuaJ67GSop6lE7/Y+Kbx/kY/cqp3nzL0rMLzx40yOlPK8tggD8MkQQs2fwBEHv2xlDZZzb0u9LTD5mS2CddsDcASu1KVzUzYT5wVwEqMT3I5yZ/bTyDh7YuMNaukDkltBONobaFyZm8MyQyHIpU=
